name: Deploy Sharelatex Full
run-name: ${{ gitea.actor }} is deploying ${{ vars.repository }}
on:
  workflow_dispatch:
    inputs:
      sharelatex_version:
        description: "The version of ShareLaTeX to deploy"
        required: true
        default: "latest"
  schedule:
    - cron: '@daily'



jobs:
  get-current-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.export-var.outputs.VERSION }}
    steps:
      - name: Get current Version
        run: |
          curl https://raw.githubusercontent.com/overleaf/toolkit/refs/heads/master/lib/config-seed/version
          VERSION=$(curl https://raw.githubusercontent.com/overleaf/toolkit/refs/heads/master/lib/config-seed/version)
          echo "VERSION=$VERSION"  >> $GITHUB_ENV
      
      - name: Export Variable
        id: export-var
        run: |
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

  automatic-build-and-deploy:
    runs-on: ubuntu-latest
    needs: get-current-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ${{ vars.URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        env:
          SHARELATEX_VERSION: ${{ github.event.inputs.sharelatex_version }}
        run: docker build --build-arg SHARELATEX_VERSION=${{ needs.get-current-version.outputs.VERSION }} -t ${{ vars.URL }}/${{ vars.repository }}:${{ needs.get-current-version.outputs.VERSION }} .

      - name: Push image
        run: docker push ${{ vars.URL }}/${{ vars.repository }}:${{ needs.get-current-version.outputs.VERSION }}   

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      
      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ${{ vars.URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        env:
          SHARELATEX_VERSION: ${{ github.event.inputs.sharelatex_version }}
        run: docker build --build-arg SHARELATEX_VERSION=${{ env.SHARELATEX_VERSION }} -t ${{ vars.URL }}/${{ vars.repository }}:${{ env.SHARELATEX_VERSION }} .

      - name: Push image
        env:
          SHARELATEX_VERSION: ${{ github.event.inputs.sharelatex_version }}
        run: docker push ${{ vars.URL }}/${{ vars.repository }}:${{ env.SHARELATEX_VERSION }}    